version: "3"
networks:
  mqtt:
services:
  master:
    image: eclipse-mosquitto
    expose:
      - "1883"
    volumes:
      - "./config/mosquitto-master.conf:/mosquitto/config/mosquitto.conf"
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
    networks:
      - mqtt
    depends_on:
      - slave
    
  slave:
    image: eclipse-mosquitto
    expose:
      - "1883"
    volumes:
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
    networks:
      - mqtt
  
  subscriber:
    build:
      context: ./
      dockerfile: ./Dockerfile-subscriber
    networks:
      - mqtt
    depends_on:
      - master
      - slave